// UK lang variables

tinymce.addI18n('en' { 'imgmap': {
  "title" : 'Image Map Editor',
  "desc" : 'Image Map Editor',
  "btnUpdate" : 'Update',
  "btnCancel" : 'Cancel',
  "btnRemove" : 'Remove map',
  "add_new_area" : 'Add new area',
  "delete_area" : 'Remove area',
  "get_image_map": "Get image map HTML",
  "img_map_areas" : 'Definitions',
  "img_map_zoom" : 'Zoom',
  "img_bounding_box" : 'Bounding',
  "img_bounding_no_label" : 'without label',
  "img_bounding_label_with_number" : 'with numbers',
  "img_bounding_label_with_href" : 'with hyperlinks',
  "img_bounding_label_with_coords" : 'with coordinates',
  "img_image" : 'Bild',
  "img_status" : 'Aktions Status',
  "FRM_CONTAINER_INFOBASE" : 'Select record',
  "FRM_CONTAINER_COORD" : 'Coordinates',
  "FRM_CONTAINER_HREF" : 'Link',
  "FRM_CONTAINER_TARGET" : 'Target',
  "FRM_CONTAINER_TRGT_NEW" : 'New window',
  "FRM_CONTAINER_TRGT_THIS" : 'This window',
  "FRM_CONTAINER_TRGT_TOP" : 'This page',
  "FRM_CONTAINER_TYP_RECT" : 'Rectangle',
  "FRM_CONTAINER_TYP_CIRC" : 'Circle',
  "FRM_CONTAINER_TYP_POLY" : 'Polygon',
  "READY" : 'Ready',
  "PREVIEW_MODE" : 'Preview mode. Test your image map.',
  "DESIGN_MODE" : 'Design mode. Add new shapes or modify existing ones.',
  "HINT_ADD" : 'Add new area',
  "HINT_DELETE" : 'Delete selected area',
  "HINT_PREVIEW" : 'Preview image map',
  "HINT_HTML" : 'Get image map HTML',
  "HINT_CLIPBOARD" : 'Copy to clipboard',
  "RECTANGLE_DRAW" : 'Drawing rectangle. Hold down SHIFT for square mode.',
  "RECTANGLE_MOVE" : 'Moving rectangle',
  "RECTANGLE_RESIZE_TOP" : 'Resizing rectangle',
  "RECTANGLE_RESIZE_RIGHT" : 'Resizing rectangle',
  "RECTANGLE_RESIZE_BOTTOM" : 'Resizing rectangle',
  "RECTANGLE_RESIZE_LEFT" : 'Resizing rectangle',
  "SQUARE_DRAW" : 'Drawing circle',
  "SQUARE2_DRAW" : 'Drawing square. Release SHIFT for rectangle mode.',
  "SQUARE_MOVE" : 'Moving circle',
  "SQUARE_RESIZE_TOP" : 'Resizing circle',
  "SQUARE_RESIZE_RIGHT" : 'Resizing circle',
  "SQUARE_RESIZE_BOTTOM" : 'Resizing circle',
  "SQUARE_RESIZE_LEFT" : 'Resizing circle',
  "POLYGON_DRAW" : 'Drawing polygon. Use SHIFT + click for the last control point.',
  "POLYGON_MOVE" : 'Moving polygon',
  "ERR_EXCANVAS_LOAD" : 'Excanvas not loaded properly. Try to refresh the page.',
  "ERR_INVALID_COORDS" : 'Invalid coordinates.'  
}});
