// FR lang variables

tinymce.addI18n('fr' { 'imgmap': {
  "title" : 'Image Map Editor',
  "desc" : 'Image Map Editor',
  "btnUpdate" : 'Mettre à jour',
  "btnCancel" : 'Abandonner',
  "btnRemove" : 'Supprimer la map',
  "add_new_area" : 'Add new area',
  "delete_area" : 'Remove area',
  "get_image_map": "Get image map HTML",
  "img_map_areas" : 'Definitions',
  "img_map_zoom" : 'Zoom',
  "img_bounding_box" : 'Bounding',
  "img_bounding_no_label" : 'without label',
  "img_bounding_label_with_number" : 'with numbers',
  "img_bounding_label_with_href" : 'with hyperlinks',
  "img_bounding_label_with_coords" : 'with coordinates',
  "img_image" : 'Bild',
  "img_status" : 'Aktions Status',
  "FRM_CONTAINER_INFOBASE" : 'Select record',
  "FRM_CONTAINER_COORD" : 'Coordinates',
  "FRM_CONTAINER_HREF" : 'Link',
  "FRM_CONTAINER_TARGET" : 'Target',
  "FRM_CONTAINER_TRGT_NEW" : 'New window',
  "FRM_CONTAINER_TRGT_THIS" : 'This window',
  "FRM_CONTAINER_TRGT_TOP" : 'This page',
  "FRM_CONTAINER_TYP_RECT" : 'Rectangle',
  "FRM_CONTAINER_TYP_CIRC" : 'Circle',
  "FRM_CONTAINER_TYP_POLY" : 'Polygon',
  "READY" : "Pret",
  "PREVIEW_MODE" : "Mode pre-visualisation. Test de l'image",
  "DESIGN_MODE" : "Mode design. Ajou de nouvelles formes ou modification des existantes",
  "HINT_ADD" : "Ajouter une nouvelle zone",
  "HINT_DELETE" : "Detruire la zone selectionnee",
  "HINT_PREVIEW" : "Pre-visualiser l'image",
  "HINT_HTML" : "Obtenir l'image HTML",
  "HINT_CLIPBOARD" : "Copier dans le presse papier",
  "RECTANGLE_DRAW" : "Dessiner un rectangle. Maintenir enfoncer la touche SHIFT pour le mode carre",
  "RECTANGLE_MOVE" : "Deplacer le rectangle",
  "RECTANGLE_RESIZE_TOP" : "Redimensionner le rectangle",
  "RECTANGLE_RESIZE_RIGHT" : "Redimensionner le rectangle",
  "RECTANGLE_RESIZE_BOTTOM" : "Redimensionner le rectangle",
  "RECTANGLE_RESIZE_LEFT" : "Redimensionner le rectangle",
  "SQUARE_DRAW" : "Dessiner un cercle",
  "SQUARE2_DRAW" : "Dessiner un carre. Relacher la touche SHIFT pour le mode rectangle",
  "SQUARE_MOVE" : "Deplacer le carre",
  "SQUARE_RESIZE_TOP" : "Redimensionner le carre",
  "SQUARE_RESIZE_RIGHT" : "Redimensionner le carre",
  "SQUARE_RESIZE_BOTTOM" : "Redimensionner le carre",
  "SQUARE_RESIZE_LEFT" : "Redimensionner le carre",
  "POLYGON_DRAW" : "Dessiner un polygone. Utiliser SHIFT + Click pour le dernier point de controle",
  "POLYGON_MOVE" : "Deplacer le polygone",
  "ERR_EXCANVAS_LOAD" : "Erreur de chargement Excanvas. Essayez de rafraichir la page",
  "ERR_INVALID_COORDS" : "Coordonnees invalides"	
}});
