// FR lang variables

tinymce.addI18n('fr', { 'imgmap': {
  "title" : 'Image Map Editor',
  "desc" : 'Image Map Editor',
  "btnUpdate" : 'Mettre à jour',
  "btnCancel" : 'Abandonner',
  "btnRemove" : 'Supprimer la map',
  "add_new_area" : 'Ajouter une nouvelle zone',
  "delete_area" : 'Supprimer la zone',
  "get_image_map": "Récuperer le code HTML",
  "img_map_areas" : 'Définitions',
  "img_map_zoom" : 'Zoom',
  "img_bounding_box" : 'Limites',
  "img_bounding_no_label" : 'sans label',
  "img_bounding_label_with_number" : 'sans numéro',
  "img_bounding_label_with_href" : 'sans lien',
  "img_bounding_label_with_coords" : 'sans coordonnée',
  "img_image" : 'Image',
  "img_status" : 'Status',
  "FRM_CONTAINER_INFOBASE" : 'Select record',
  "FRM_CONTAINER_COORD" : 'Coordonnée',
  "FRM_CONTAINER_HREF" : 'Lien',
  "FRM_CONTAINER_TARGET" : 'Cible',
  "FRM_CONTAINER_TRGT_NEW" : 'Nouvelle fenêtre',
  "FRM_CONTAINER_TRGT_THIS" : 'Cette fenêtre',
  "FRM_CONTAINER_TRGT_TOP" : 'Cette page',
  "FRM_CONTAINER_TYP_RECT" : 'Rectangle',
  "FRM_CONTAINER_TYP_CIRC" : 'Cercle',
  "FRM_CONTAINER_TYP_POLY" : 'Polygone',
  "READY" : "Prêt",
  "PREVIEW_MODE" : "Mode pre-visualisation. Test de l'image",
  "DESIGN_MODE" : "Mode design. Ajout de nouvelles formes ou modification des existantes",
  "HINT_ADD" : "Ajouter une nouvelle zone",
  "HINT_DELETE" : "Détruire la zone selectionnée",
  "HINT_PREVIEW" : "Pre-visualiser l'image",
  "HINT_HTML" : "Obtenir le code HTML",
  "HINT_CLIPBOARD" : "Copier dans le presse papier",
  "RECTANGLE_DRAW" : "Dessiner un rectangle. Maintenir enfoncer la touche SHIFT pour le mode carre",
  "RECTANGLE_MOVE" : "Deplacer le rectangle",
  "RECTANGLE_RESIZE_TOP" : "Redimensionner le rectangle",
  "RECTANGLE_RESIZE_RIGHT" : "Redimensionner le rectangle",
  "RECTANGLE_RESIZE_BOTTOM" : "Redimensionner le rectangle",
  "RECTANGLE_RESIZE_LEFT" : "Redimensionner le rectangle",
  "SQUARE_DRAW" : "Dessiner un cercle",
  "SQUARE2_DRAW" : "Dessiner un carré. Relacher la touche SHIFT pour le mode rectangle",
  "SQUARE_MOVE" : "Déplacer le carré",
  "SQUARE_RESIZE_TOP" : "Redimensionner le carré",
  "SQUARE_RESIZE_RIGHT" : "Redimensionner le carré",
  "SQUARE_RESIZE_BOTTOM" : "Redimensionner le carré",
  "SQUARE_RESIZE_LEFT" : "Redimensionner le carré",
  "POLYGON_DRAW" : "Déssiner un polygone. Utiliser SHIFT + Click pour le dernier point de controle",
  "POLYGON_MOVE" : "Déplacer le polygone",
  "ERR_EXCANVAS_LOAD" : "Erreur de chargement Excanvas. Essayez de rafraichir la page",
  "ERR_INVALID_COORDS" : "Coordonnées invalides"
}});
